// Periodic Table Elements Data (1-118)
const elements = {
    1: { symbol: 'H', name: '수소', nameEn: 'Hydrogen' },
    2: { symbol: 'He', name: '헬륨', nameEn: 'Helium' },
    3: { symbol: 'Li', name: '리튬', nameEn: 'Lithium' },
    4: { symbol: 'Be', name: '베릴륨', nameEn: 'Beryllium' },
    5: { symbol: 'B', name: '붕소', nameEn: 'Boron' },
    6: { symbol: 'C', name: '탄소', nameEn: 'Carbon' },
    7: { symbol: 'N', name: '질소', nameEn: 'Nitrogen' },
    8: { symbol: 'O', name: '산소', nameEn: 'Oxygen' },
    9: { symbol: 'F', name: '플루오린', nameEn: 'Fluorine' },
    10: { symbol: 'Ne', name: '네온', nameEn: 'Neon' },
    11: { symbol: 'Na', name: '나트륨', nameEn: 'Sodium' },
    12: { symbol: 'Mg', name: '마그네슘', nameEn: 'Magnesium' },
    13: { symbol: 'Al', name: '알루미늄', nameEn: 'Aluminum' },
    14: { symbol: 'Si', name: '규소', nameEn: 'Silicon' },
    15: { symbol: 'P', name: '인', nameEn: 'Phosphorus' },
    16: { symbol: 'S', name: '황', nameEn: 'Sulfur' },
    17: { symbol: 'Cl', name: '염소', nameEn: 'Chlorine' },
    18: { symbol: 'Ar', name: '아르곤', nameEn: 'Argon' },
    19: { symbol: 'K', name: '칼륨', nameEn: 'Potassium' },
    20: { symbol: 'Ca', name: '칼슘', nameEn: 'Calcium' },
    21: { symbol: 'Sc', name: '스칸듐', nameEn: 'Scandium' },
    22: { symbol: 'Ti', name: '타이타늄', nameEn: 'Titanium' },
    23: { symbol: 'V', name: '바나듐', nameEn: 'Vanadium' },
    24: { symbol: 'Cr', name: '크롬', nameEn: 'Chromium' },
    25: { symbol: 'Mn', name: '망간', nameEn: 'Manganese' },
    26: { symbol: 'Fe', name: '철', nameEn: 'Iron' },
    27: { symbol: 'Co', name: '코발트', nameEn: 'Cobalt' },
    28: { symbol: 'Ni', name: '니켈', nameEn: 'Nickel' },
    29: { symbol: 'Cu', name: '구리', nameEn: 'Copper' },
    30: { symbol: 'Zn', name: '아연', nameEn: 'Zinc' },
    31: { symbol: 'Ga', name: '갈륨', nameEn: 'Gallium' },
    32: { symbol: 'Ge', name: '게르마늄', nameEn: 'Germanium' },
    33: { symbol: 'As', name: '비소', nameEn: 'Arsenic' },
    34: { symbol: 'Se', name: '셀레늄', nameEn: 'Selenium' },
    35: { symbol: 'Br', name: '브롬', nameEn: 'Bromine' },
    36: { symbol: 'Kr', name: '크립톤', nameEn: 'Krypton' },
    37: { symbol: 'Rb', name: '루비듐', nameEn: 'Rubidium' },
    38: { symbol: 'Sr', name: '스트론튬', nameEn: 'Strontium' },
    39: { symbol: 'Y', name: '이트륨', nameEn: 'Yttrium' },
    40: { symbol: 'Zr', name: '지르코늄', nameEn: 'Zirconium' },
    41: { symbol: 'Nb', name: '나이오븀', nameEn: 'Niobium' },
    42: { symbol: 'Mo', name: '몰리브덴', nameEn: 'Molybdenum' },
    43: { symbol: 'Tc', name: '테크네튬', nameEn: 'Technetium' },
    44: { symbol: 'Ru', name: '루테늄', nameEn: 'Ruthenium' },
    45: { symbol: 'Rh', name: '로듐', nameEn: 'Rhodium' },
    46: { symbol: 'Pd', name: '팔라듐', nameEn: 'Palladium' },
    47: { symbol: 'Ag', name: '은', nameEn: 'Silver' },
    48: { symbol: 'Cd', name: '카드뮴', nameEn: 'Cadmium' },
    49: { symbol: 'In', name: '인듐', nameEn: 'Indium' },
    50: { symbol: 'Sn', name: '주석', nameEn: 'Tin' },
    51: { symbol: 'Sb', name: '안티몬', nameEn: 'Antimony' },
    52: { symbol: 'Te', name: '텔루륨', nameEn: 'Tellurium' },
    53: { symbol: 'I', name: '아이오딘', nameEn: 'Iodine' },
    54: { symbol: 'Xe', name: '제논', nameEn: 'Xenon' },
    55: { symbol: 'Cs', name: '세슘', nameEn: 'Cesium' },
    56: { symbol: 'Ba', name: '바륨', nameEn: 'Barium' },
    57: { symbol: 'La', name: '란타넘', nameEn: 'Lanthanum' },
    58: { symbol: 'Ce', name: '세륨', nameEn: 'Cerium' },
    59: { symbol: 'Pr', name: '프라세오디뮴', nameEn: 'Praseodymium' },
    60: { symbol: 'Nd', name: '네오디뮴', nameEn: 'Neodymium' },
    61: { symbol: 'Pm', name: '프로메튬', nameEn: 'Promethium' },
    62: { symbol: 'Sm', name: '사마륨', nameEn: 'Samarium' },
    63: { symbol: 'Eu', name: '유로퓸', nameEn: 'Europium' },
    64: { symbol: 'Gd', name: '가돌리늄', nameEn: 'Gadolinium' },
    65: { symbol: 'Tb', name: '터븀', nameEn: 'Terbium' },
    66: { symbol: 'Dy', name: '디스프로슘', nameEn: 'Dysprosium' },
    67: { symbol: 'Ho', name: '홀뮴', nameEn: 'Holmium' },
    68: { symbol: 'Er', name: '어븀', nameEn: 'Erbium' },
    69: { symbol: 'Tm', name: '툴륨', nameEn: 'Thulium' },
    70: { symbol: 'Yb', name: '이터븀', nameEn: 'Ytterbium' },
    71: { symbol: 'Lu', name: '루테튬', nameEn: 'Lutetium' },
    72: { symbol: 'Hf', name: '하프늄', nameEn: 'Hafnium' },
    73: { symbol: 'Ta', name: '탄탈럼', nameEn: 'Tantalum' },
    74: { symbol: 'W', name: '텅스텐', nameEn: 'Tungsten' },
    75: { symbol: 'Re', name: '레늄', nameEn: 'Rhenium' },
    76: { symbol: 'Os', name: '오스뮴', nameEn: 'Osmium' },
    77: { symbol: 'Ir', name: '이리듐', nameEn: 'Iridium' },
    78: { symbol: 'Pt', name: '백금', nameEn: 'Platinum' },
    79: { symbol: 'Au', name: '금', nameEn: 'Gold' },
    80: { symbol: 'Hg', name: '수은', nameEn: 'Mercury' },
    81: { symbol: 'Tl', name: '탈륨', nameEn: 'Thallium' },
    82: { symbol: 'Pb', name: '납', nameEn: 'Lead' },
    83: { symbol: 'Bi', name: '비스무트', nameEn: 'Bismuth' },
    84: { symbol: 'Po', name: '폴로늄', nameEn: 'Polonium' },
    85: { symbol: 'At', name: '아스타틴', nameEn: 'Astatine' },
    86: { symbol: 'Rn', name: '라돈', nameEn: 'Radon' },
    87: { symbol: 'Fr', name: '프랑슘', nameEn: 'Francium' },
    88: { symbol: 'Ra', name: '라듐', nameEn: 'Radium' },
    89: { symbol: 'Ac', name: '악티늄', nameEn: 'Actinium' },
    90: { symbol: 'Th', name: '토륨', nameEn: 'Thorium' },
    91: { symbol: 'Pa', name: '프로트악티늄', nameEn: 'Protactinium' },
    92: { symbol: 'U', name: '우라늄', nameEn: 'Uranium' },
    93: { symbol: 'Np', name: '넵투늄', nameEn: 'Neptunium' },
    94: { symbol: 'Pu', name: '플루토늄', nameEn: 'Plutonium' },
    95: { symbol: 'Am', name: '아메리슘', nameEn: 'Americium' },
    96: { symbol: 'Cm', name: '퀴륨', nameEn: 'Curium' },
    97: { symbol: 'Bk', name: '버클륨', nameEn: 'Berkelium' },
    98: { symbol: 'Cf', name: '캘리포늄', nameEn: 'Californium' },
    99: { symbol: 'Es', name: '아인슈타이늄', nameEn: 'Einsteinium' },
    100: { symbol: 'Fm', name: '페르뮴', nameEn: 'Fermium' },
    101: { symbol: 'Md', name: '멘델레븀', nameEn: 'Mendelevium' },
    102: { symbol: 'No', name: '노벨륨', nameEn: 'Nobelium' },
    103: { symbol: 'Lr', name: '로렌슘', nameEn: 'Lawrencium' },
    104: { symbol: 'Rf', name: '러더포듐', nameEn: 'Rutherfordium' },
    105: { symbol: 'Db', name: '더브늄', nameEn: 'Dubnium' },
    106: { symbol: 'Sg', name: '시보귬', nameEn: 'Seaborgium' },
    107: { symbol: 'Bh', name: '보륨', nameEn: 'Bohrium' },
    108: { symbol: 'Hs', name: '하슘', nameEn: 'Hassium' },
    109: { symbol: 'Mt', name: '마이트너륨', nameEn: 'Meitnerium' },
    110: { symbol: 'Ds', name: '다름슈타튬', nameEn: 'Darmstadtium' },
    111: { symbol: 'Rg', name: '뢴트게늄', nameEn: 'Roentgenium' },
    112: { symbol: 'Cn', name: '코페르니슘', nameEn: 'Copernicium' },
    113: { symbol: 'Nh', name: '니호늄', nameEn: 'Nihonium' },
    114: { symbol: 'Fl', name: '플레로븀', nameEn: 'Flerovium' },
    115: { symbol: 'Mc', name: '모스코븀', nameEn: 'Moscovium' },
    116: { symbol: 'Lv', name: '리버모륨', nameEn: 'Livermorium' },
    117: { symbol: 'Ts', name: '테네신', nameEn: 'Tennessine' },
    118: { symbol: 'Og', name: '오가네손', nameEn: 'Oganesson' }
};

// Function to get element data by atomic number
function getElement(atomicNumber) {
    if (atomicNumber < 1 || atomicNumber > 118) {
        return {
            symbol: `[${atomicNumber}]`,
            name: '미지의 원소',
            nameEn: 'Unknown'
        };
    }
    return elements[atomicNumber];
}